language: python
python:
    - "2.7"
before_install:
    - sudo apt-get install python-dev libboost-dev libboost-python-dev libboost-thread-dev libboost-system-dev
    - git clone --depth=50 --branch=master https://github.com/qistoph/pyv8.git qistoph/pyv8
    - pushd qistoph/pyv8
    - python setup.py build
    - sudo python setup.py install
    - popd
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: ./checks/run.sh
